/* eslint-disable react-hooks/rules-of-hooks */
import Head from "next/head";
import { useRouter } from "next/router";
import Error from "next/error";
import { initializeApollo } from "../backend/client";
import CreatTaskForm from "../components/CreateTaskForm";
import TaskList from "../components/TaskList";
import {
  TasksDocument,
  TasksQuery,
  TasksQueryVariables,
  TaskStatus,
  useTasksQuery,
} from "../generated/graphql-frontend";
import { useEffect, useRef } from "react";
import TaskFilter from "../components/TaskFilter";
import { GetServerSideProps } from "next";
import Custom404 from "./404";

const isTaskStatus = (value: string): value is TaskStatus =>
  Object.values(TaskStatus).includes(value as TaskStatus);

export default function Home() {
  const router = useRouter();
  const status =
    Array.isArray(router.query.status) && router.query.status.length
      ? (router.query.status[0] as TaskStatus)
      : undefined;

  if (status !== undefined && !isTaskStatus(status)) {
    return <Custom404 />;
  }

  const prevStatus = useRef(status);

  useEffect(() => {
    prevStatus.current = status;
  }, [status]);

  const result = useTasksQuery({
    variables: { status },
    fetchPolicy:
      prevStatus.current === status ? "cache-first" : "cache-and-network",
  });
  const tasks = result.data?.tasks;

  return (
    <div>
      <Head>
        <title>Tasks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CreatTaskForm onSuccess={result.refetch} />
        {result.loading ? (
          <p>Loading ...</p>
        ) : tasks && tasks.length > 0 ? (
          <TaskList tasks={tasks} />
        ) : (
          <p className="no-tasks-message">You&apos;ve got no tasks.</p>
        )}
        <TaskFilter status={status} />
      </main>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const status =
    typeof context.params?.status === "string"
      ? (context.params.status as TaskStatus)
      : undefined;

  if (status === undefined && !isTaskStatus(status)) {
    const apolloClient = initializeApollo();

    await apolloClient.query<TasksQuery, TasksQueryVariables>({
      query: TasksDocument,
      variables: { status },
    });

    return {
      props: {
        initialApolloState: apolloClient.cache.extract(),
      },
    };
  }

  return { props: {} };
};
