import Head from "next/head";
import { initializeApollo } from "../backend/client";
import TaskList from "../components/TaskList";
import {
  TasksDocument,
  TasksQuery,
  useTasksQuery,
} from "../generated/graphql-frontend";

export default function Home() {
  const result = useTasksQuery();
  const tasks = result.data.tasks;

  return (
    <div>
      <Head>
        <title>Tasks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {result.loading ? (
          <p>Loading ...</p>
        ) : tasks && tasks.length > 0 ? (
          <TaskList tasks={tasks} />
        ) : (
          <p className="no-tasks-message">You&apos;ve got no tasks.</p>
        )}
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const apolloClient = initializeApollo();

  await apolloClient.query<TasksQuery>({
    query: TasksDocument,
  });

  return {
    props: {
      initialApolloState: apolloClient.cache.extract(),
    },
  };
};
